# 1. A f&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units.A randomly selected sample of cutlets was collected from both units and measured? Analyse the data and draw inferences at 5% significance level. Please state the assumptions and test you carried out to check validity of the assumptions

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from scipy import stats

In [3]:
cutlets_data= pd.read_csv("D:/data_structure/hypotesis_testing_level_3/Cutlets.csv")
cutlets_data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

# Hypothesis Testing
H0 : There is no significant difference in the diameter of cutlet between two units

H1 : There is a significant differnce in the diameter of cutlet between two units

LOS : 5%

In [4]:
cutlets_data.isnull().sum()

Unit A    0
Unit B    0
dtype: int64

# UNIT A

In [5]:
unit_A=cutlets_data["Unit A"]
unit_A.head()

0    6.8090
1    6.4376
2    6.9157
3    7.3012
4    7.4488
Name: Unit A, dtype: float64

In [6]:
unit_A.mean()

7.01909142857143

In [7]:
round(unit_A.mean())

7

# UNIT B 

In [8]:
unit_B=cutlets_data["Unit B"]
unit_B.head()

0    6.7703
1    7.5093
2    6.7300
3    6.7878
4    7.1522
Name: Unit B, dtype: float64

In [9]:
unit_B.mean()

6.964297142857142

In [10]:
round(unit_B.mean())

7

# Observation :
As the mean of Unit A and Unit B are equal there is no significant difference between the units
P_Value :

In [11]:
t_test,p_val=stats.ttest_ind(  a=unit_A ,b=unit_B)
t_test,p_val

(0.7228688704678063, 0.4722394724599501)

# Conclusion :

# There is no significant difference in the diameter of cutlet between two units,we fail to reject null hypothesis 

# 2. A Hospital wants to detrmine whether there is any differnce in the average Turn Around Time of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories, TAT is deffined as samplecollected to report dispatch.Analyze the data and determine whether there is any differnce in average TAT among the different laboratories at 5% significance level

In [12]:
lab_data=pd.read_csv("D:\data_structure\hypotesis_testing_level_3\LabTAT.csv")
lab_data

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

# Hypothesis Testing
H0 : There is no significant difference in average Turn Around Time of reports of different laboratories

H1 : There is a significant differnce in the average Turn Around Time of differnt laboratories

LOS : 5%

# Data Analysis

In [14]:
lab_data.isnull().sum()


Laboratory 1    0
Laboratory 2    0
Laboratory 3    0
Laboratory 4    0
dtype: int64

In [15]:
lab_data.dtypes

Laboratory 1    float64
Laboratory 2    float64
Laboratory 3    float64
Laboratory 4    float64
dtype: object

In [16]:
lab_1=lab_data['Laboratory 1'].head()
lab_1

0    185.35
1    170.49
2    192.77
3    177.33
4    193.41
Name: Laboratory 1, dtype: float64

In [17]:
lab_1.mean()

183.87

In [18]:
lab_2=lab_data['Laboratory 2'].head()
lab_2

0    165.53
1    185.91
2    194.92
3    183.00
4    169.57
Name: Laboratory 2, dtype: float64

In [19]:
lab_2.mean()

179.786

In [20]:
lab_3=lab_data['Laboratory 3'].head()
lab_3

0    176.70
1    198.45
2    201.23
3    199.61
4    204.63
Name: Laboratory 3, dtype: float64

In [21]:
lab_3.mean()

196.124

In [22]:
lab_4=lab_data['Laboratory 4'].head()
lab_4

0    166.13
1    160.79
2    185.18
3    176.42
4    152.60
Name: Laboratory 4, dtype: float64

In [23]:
lab_4.mean()

168.224

# Observation:
From the above analysis we can see that mean values of 4 different laboratories are not same

ANOVA Test

In [25]:
statsics,pvalue=stats.f_oneway(lab_1,lab_2,lab_3,lab_4)
statsics,pvalue

(4.977657221773666, 0.012559049971997725)

# Conclusion :


# there is a significant differnce in the average Turn Around Time of 4 laboratories, we reject null hypothesis

# 3.Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [26]:
import pandas as pd
from scipy import stats
from scipy.stats import chi2

In [27]:
df=pd.read_csv("D:\data_structure\hypotesis_testing_level_3\BuyerRatio.csv")
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [28]:
df_table = df.iloc[:,1:5]
df_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

# Hypothesis Testing
H0 : There is no significant all proportions are equal

H1 : There is a significant differnce all proportions are not equal

LOS : 5%

In [29]:
df_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [30]:
val = stats.chi2_contingency(df_table)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [31]:
type(val)

tuple

# Degree of freedom

In [32]:
no_of_rows = len(df_table.iloc[0:2,0])
no_of_columns = len(df_table.iloc[0,0:4])
dof=(no_of_rows-1)*(no_of_columns-1)
print('Degree of freedom=',dof)

Degree of freedom= 3


# Expected value

In [34]:
Expected_value =val[3]
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [35]:
chi_square = sum([(o-e)**2/e for o,e in zip(df_table.values,Expected_value)])
chi_square_statistic = chi_square[0]+chi_square[1]
chi_square_statistic

1.5152956451130446

# Critical value

In [36]:
Critical_value = chi2.ppf(0.95,3)
Critical_value

7.814727903251179

In [37]:
if chi_square_statistic >= Critical_value:
    print('we reject H0,There is a significant differnce')
else:
    print('we fail to reject H0, there is no significant differnce')

we fail to reject H0, there is no significant differnce


In [38]:
p_value =1-chi2.cdf(chi_square_statistic,3)
p_value

0.6787446296467897

In [39]:
if p_value<0.05:
    print('we reject H0,There is a significant differnce')
else:
    print('we fail to reject H0, there is no significant differnce')

we fail to reject H0, there is no significant differnce


# 4.TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain % of the customer order forms. Any error in order form renders it defective and has to be reworked before processing. The manager wants to check whether the defective % varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences

In [40]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import  chi2_contingency

In [41]:
data=pd.read_csv("D:\data_structure\hypotesis_testing_level_3\Costomer+OrderForm.csv")
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

# Hypothesis Testing
H0 : defective % varies by center

H1 : Defectives % doesn't varies by center

LOS : 5%

# 

In [43]:
data.Phillippines.value_counts() 

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [44]:
data.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [45]:
data.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [46]:
data.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [47]:
obs = np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [48]:
chi2_stats_value,p_value,df,expected_observatoin= chi2_contingency(obs)
print(chi2_stats_value,p_value,df,expected_observatoin)

3.858960685820355 0.2771020991233135 3 [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [49]:
if p_value >0.05:
    print('Defective % varies by center')
else:
    print("Defective % doesn't vary by center")

Defective % varies by center
